export { h } from './h'
export { renderSlot } from './helpers/renderSlot'
export { createTextVNode } from './createVNode'
export { getCurrentInstance } from './component'
export { provide, inject } from './apiInject'
export { createRenderer } from './render'
