export { createApp } from './createApp'
export { h } from './h'
export { renderSlot } from './helpers/renderSlot'
export { createTextVNode } from './createVNode'
export { getCurrentInstance } from './component'
